//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod categories;
pub mod payment_methods;
pub mod permissions;
pub mod products;
pub mod profile_permissions;
pub mod profiles;
pub mod refund_details;
pub mod refunds;
pub mod sale_details;
pub mod sale_payments;
pub mod sales;
pub mod users;
