//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "payment_methods")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_payment: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub is_active: bool,
    #[sea_orm(unique)]
    pub sat_key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sales::Entity")]
    Sales,
}

impl Related<super::sales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sales.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
