//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "permissions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub code: String,
    pub name: String,
    pub module: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::profile_permissions::Entity")]
    ProfilePermissions,
}

impl Related<super::profile_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfilePermissions.def()
    }
}

impl Related<super::profiles::Entity> for Entity {
    fn to() -> RelationDef {
        super::profile_permissions::Relation::Profiles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::profile_permissions::Relation::Permissions
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
