//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub category_id: Option<i32>,
    #[sea_orm(unique)]
    pub code: String,
    pub stock: i32,
    pub is_active: bool,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub cost: Decimal,
    #[sea_orm(column_type = "Decimal(Some((5, 4)))")]
    pub tax: Decimal,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: String,
    pub updated_by: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::CategoryId",
        to = "super::categories::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Categories,
    #[sea_orm(has_many = "super::refund_details::Entity")]
    RefundDetails,
    #[sea_orm(has_many = "super::sale_details::Entity")]
    SaleDetails,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedBy",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users1,
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::refund_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefundDetails.def()
    }
}

impl Related<super::sale_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleDetails.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
