//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "profiles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub is_active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::profile_permissions::Entity")]
    ProfilePermissions,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
}

impl Related<super::profile_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfilePermissions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::profile_permissions::Relation::Permissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::profile_permissions::Relation::Profiles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
