//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "refounds")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_refound: i32,
    pub sale_id: i32,
    pub date: DateTime,
    pub reason: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::refound_details::Entity")]
    RefoundDetails,
}

impl Related<super::refound_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefoundDetails.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
