//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sales")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub subtotal: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub total: Decimal,
    pub status: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: String,
    pub updated_by: String,
    pub shift_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::refunds::Entity")]
    Refunds,
    #[sea_orm(has_many = "super::sale_details::Entity")]
    SaleDetails,
    #[sea_orm(has_many = "super::sale_payments::Entity")]
    SalePayments,
    #[sea_orm(
        belongs_to = "super::shifts::Entity",
        from = "Column::ShiftId",
        to = "super::shifts::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Shifts,
    #[sea_orm(has_many = "super::ticket_prints::Entity")]
    TicketPrints,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedBy",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users1,
}

impl Related<super::refunds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Refunds.def()
    }
}

impl Related<super::sale_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleDetails.def()
    }
}

impl Related<super::sale_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalePayments.def()
    }
}

impl Related<super::shifts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shifts.def()
    }
}

impl Related<super::ticket_prints::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TicketPrints.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
