//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sale_payments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_payment: i32,
    pub sale_id: i32,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub total: Decimal,
    pub reference: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sales::Entity",
        from = "Column::SaleId",
        to = "super::sales::Column::IdSale",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Sales,
}

impl Related<super::sales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sales.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
