//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sales")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_sale: i32,
    pub created_at: DateTime,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub total: Decimal,
    pub payment_method: i32,
    pub status: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethod",
        to = "super::payment_methods::Column::IdPayment",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PaymentMethods,
    #[sea_orm(has_many = "super::sale_payments::Entity")]
    SalePayments,
    #[sea_orm(has_many = "super::sales_details::Entity")]
    SalesDetails,
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::sale_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalePayments.def()
    }
}

impl Related<super::sales_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalesDetails.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
