//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sale_details")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sale_id: String,
    pub product_id: i32,
    pub quantity: i32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub unit_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub subtotal: Decimal,
    #[sea_orm(column_type = "Decimal(Some((5, 4)))")]
    pub tax_rate: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub tax_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub total: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Products,
    #[sea_orm(
        belongs_to = "super::sales::Entity",
        from = "Column::SaleId",
        to = "super::sales::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Sales,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::sales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sales.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
